version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: MPI_PROD_NEW
    ports:
      - "1433:1433"

  node-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - sql-server
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    command: npm run dev
    environment:
      DB_USER: "sa"
      DB_PASSWORD: "P@ssw0rd"
      DB_SERVER: "172.19.0.2"
      DB_DATABASE: "master"


