version: "3.8"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server-container
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: master
    ports:
      - "1433:1433"

  node-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - sql-server
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    command: npm run dev
    environment:
      DB_USER: "sa"
      DB_PASSWORD: "P@ssw0rd"
      DB_SERVER: "sql-server"
