export const parseCSVLine = (line) => {
  const columns = line.split(";");
  const [
    TRANSACTION_NUMBER,
    TRANSACTION_TYPE,
    CUSTOMER_NUMBER,
    ORIGINAL_AMOUNT,
    OUTSTANDING_AMOUNT,
    TRANSACTION_DATE,
    DUE_DATE,
    CLOSED_STATUS,
    TANGGAL_PELUNASAN,
    SO_NUMBER,
    BUSINESS_UNIT,
    NILAI_GIRO_MUNDUR,
  ] = columns;

  return {
    TRANSACTION_NUMBER,
    TRANSACTION_TYPE,
    CUSTOMER_NUMBER,
    ORIGINAL_AMOUNT,
    OUTSTANDING_AMOUNT,
    TRANSACTION_DATE,
    DUE_DATE,
    CLOSED_STATUS,
    TANGGAL_PELUNASAN,
    SO_NUMBER,
    BUSINESS_UNIT,
    NILAI_GIRO_MUNDUR,
  };
};
